### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by Fietspomp86** [Timmy93/M3uParser#1]
Hey,

Really like this project and I'm trying to figure out how it should work.
But I'm stuck at the config file.
Saw that I need to make a config.yml file. Did that.
But do you have a list or an example how this file should be used?
I have to following so far:

```
Settings:
  logLevel: 3
  filename: test2.m3u
  url: http://xxx.xxx.xxx.xxx/xxxxxxxxxxxxxxxxxxxxxxx
  
ExtensionFilterOut:
  value: .banaan

GroupFilterOut:
  value: DE
  
ExtensionFilterIn:
  value: .avi
  value: .ts
 
GroupFilterIn:
  value: NL
  
Download:
  db: db.m3u
```

Of course these are just example values, but I'm not getting any m3u made. It downloads the m3u fine and names it test2.m3u.
But I only get this result
```
 python3 main.py
main.py:71: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(stream)
Downloaded every file
```

So I could use some guidance how to properly make this program work.
Thanks in advance!

**Comment by Timmy93** [comment]
Hi Fietspomp86, here you can find an example of config file.
Be sure that all the directories exists. I suggest you to use 3 different directory, one for temporary files, one for files completed but to be renamed, one for the completed and renamed files.

`Settings:
  url: "http://url.to.m3u:80/getM3u.php"
  filename: "IPTV.m3u"
  logLevel: "INFO"
  
Download:
  temp_path: "/media/user/ExternalHardDisk/IPTV_Temp/in_progress/"
  completed: "/media/user/ExternalHardDisk/IPTV_Temp/complete/"
  downloader: "myDownloader.sh"
  db: "alreadyDownloaded.db"
  shuffle: false

Rename:
  source_to_rename: "/media/user/ExternalHardDisk/IPTV_Temp/complete/"
  new_dir: "/media/user/ExternalHardDisk/IPTV_Download/"

Time:
  start_time: "2:10"
  end_time: "13:10"

#Used to define the filter on the extension of the file
ExtensionFilterOut:
  value: [".ts"]

ExtensionFilterIn:
  value: []

#Used to define the filter on the group
GroupFilterOut:
  value: ["Sample Movies"]

GroupFilterIn:
  value: []
`

**Comment by Timmy93** [comment]
Hi Fietspomp86, here you can find an example of config file.
Be sure that all the directories exists. I suggest you to use 3 different directory, one for temporary files, one for files completed but to be renamed, one for the completed and renamed files.

```
Settings:
  url: "http://url.to.m3u:80/getM3u.php"
  filename: "M3U.m3u"
  logLevel: "INFO"
  
Download:
  temp_path: "/media/user/ExternalHardDisk/M3U_Temp/in_progress/"
  completed: "/media/user/ExternalHardDisk/M3U_Temp/complete/"
  downloader: "myDownloader.sh"
  db: "alreadyDownloaded.db"
  shuffle: false

Rename:
  source_to_rename: "/media/user/ExternalHardDisk/M3U_Temp/complete/"
  new_dir: "/media/user/ExternalHardDisk/M3U_Download/"

Time:
  start_time: "2:10"
  end_time: "13:10"

#Used to define the filter on the extension of the file
ExtensionFilterOut:
  value: [".ts"]

ExtensionFilterIn:
  value: []

#Used to define the filter on the group
GroupFilterOut:
  value: ["Sample Movies"]

GroupFilterIn:
  value: []
```
